# Generated by Django 3.0.5 on 2022-05-16 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacunador',
            old_name='vacunador_zona',
            new_name='vacunador_nombre',
        ),
        migrations.RemoveField(
            model_name='vacunador',
            name='vacunador_dni',
        ),
        migrations.RemoveField(
            model_name='vacunador',
            name='vacunador_email',
        ),
        migrations.RemoveField(
            model_name='vacunador',
            name='vacunador_fechaNac',
        ),
    ]
