# Generated by Django 3.0.5 on 2022-05-24 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20220523_2234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente_nombre', models.CharField(max_length=200)),
                ('paciente_apellido', models.CharField(max_length=20)),
                ('paciente_fechaNac', models.DateTimeField(verbose_name='fecha nacimiento')),
                ('paciente_zona', models.CharField(max_length=200)),
                ('paciente_dni', models.IntegerField()),
                ('paciente_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
