# Generated by Django 3.0.5 on 2022-05-24 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_administrador_vacuna_covid_vacuna_fiebre_am_vacuna_gripe_vacunatorio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='paciente_dni',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='paciente_email',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='paciente_fechaNac',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='paciente_zona',
        ),
    ]
