# Generated by Django 3.0.5 on 2022-05-24 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20220523_2246'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vacunatorio',
        ),
    ]
