# Generated by Django 3.0.5 on 2022-05-24 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_delete_vacunatorio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacunatorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('administrador_nombre', models.CharField(max_length=100)),
                ('stock_vac_fa', models.IntegerField()),
                ('stock_vac_covid', models.IntegerField()),
                ('stock_vac_gripe', models.IntegerField()),
            ],
        ),
    ]
