# Generated by Django 3.0.5 on 2022-05-24 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_vacunatorio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Administrador',
        ),
    ]
