# Generated by Django 3.0.5 on 2022-05-24 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_delete_administrador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('administrador_nombre', models.CharField(max_length=200)),
                ('administrador_apellido', models.CharField(max_length=20)),
                ('administrador_fechaNac', models.DateTimeField(verbose_name='fecha nacimiento')),
                ('administrador_zona', models.CharField(max_length=200)),
                ('administrador_dni', models.IntegerField()),
                ('administrador_contraseña', models.IntegerField()),
                ('administrador_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
