# Generated by Django 3.0.5 on 2022-05-25 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_administrador'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Administrador',
        ),
        migrations.DeleteModel(
            name='Paciente',
        ),
        migrations.DeleteModel(
            name='Vacuna_Covid',
        ),
        migrations.DeleteModel(
            name='Vacuna_Fiebre_Am',
        ),
        migrations.DeleteModel(
            name='Vacuna_Gripe',
        ),
        migrations.DeleteModel(
            name='Vacunador',
        ),
        migrations.DeleteModel(
            name='Vacunatorio',
        ),
    ]
