# Generated by Django 3.0.5 on 2022-05-25 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0012_auto_20220525_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('administrador_nombre', models.CharField(max_length=200)),
                ('administrador_apellido', models.CharField(max_length=20)),
                ('administrador_fechaNac', models.DateTimeField(verbose_name='fecha nacimiento')),
                ('administrador_zona', models.CharField(max_length=200)),
                ('administrador_dni', models.IntegerField()),
                ('administrador_contraseña', models.IntegerField()),
                ('administrador_email', models.EmailField(max_length=254)),
                ('administrador_codigo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente_nombre', models.CharField(max_length=200)),
                ('paciente_apellido', models.CharField(max_length=20)),
                ('paciente_fechaNac', models.DateTimeField(verbose_name='fecha nacimiento')),
                ('paciente_zona', models.CharField(max_length=200)),
                ('paciente_dni', models.CharField(max_length=200)),
                ('paciente_email', models.EmailField(max_length=254)),
                ('vac_Gripe_aplicada', models.SmallIntegerField(choices=[(1, 'Si'), (2, 'No')], default=2)),
                ('vac_Gripe_turno', models.DateTimeField(verbose_name='turno_gripe')),
                ('vac_Amarilla_aplicada', models.SmallIntegerField(choices=[(1, 'Si'), (2, 'No')], default=2)),
                ('vac_Amarilla_turno', models.DateTimeField(verbose_name='turno_fa')),
                ('vac_Amarilla_asistencia', models.SmallIntegerField(choices=[(1, 'Si'), (2, 'No')], default=2)),
                ('vac_Covid1_aplicada', models.SmallIntegerField(choices=[(1, 'Si'), (2, 'No')], default=2)),
                ('vac_Covid2_aplicada', models.SmallIntegerField(choices=[(1, 'Si'), (2, 'No')], default=2)),
                ('vac_Covid_turno1', models.DateTimeField(verbose_name='turno_1era')),
                ('vac_Covid_turno2', models.DateTimeField(verbose_name='turno_2da')),
                ('vac_Covid1era_asistencia', models.SmallIntegerField(choices=[(1, 'Si'), (2, 'No')], default=2)),
                ('vac_Covid2da_asistencia', models.SmallIntegerField(choices=[(1, 'Si'), (2, 'No')], default=2)),
                ('paciente_codigo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vacuna_Covid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vac_covid_nombre', models.CharField(max_length=100)),
                ('stock_vac_covid_1era', models.IntegerField()),
                ('stock_vac_covid_2da', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vacuna_Fiebre_Am',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vac_fa_nombre', models.CharField(max_length=100)),
                ('stock_vac_fa', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vacuna_Gripe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vac_gripe_nombre', models.CharField(max_length=100)),
                ('stock_vac_gripe', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vacunador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacunador_nombre', models.CharField(max_length=200)),
                ('vacunador_apellido', models.CharField(max_length=20)),
                ('vacunador_fechaNac', models.DateTimeField(verbose_name='fecha nacimiento')),
                ('vacunador_zona', models.CharField(max_length=200)),
                ('vacunador_dni', models.IntegerField()),
                ('vacunador_email', models.EmailField(max_length=254)),
                ('vacunador_codigo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vacunatorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('administrador_nombre', models.CharField(max_length=100)),
                ('stock_vac_fa', models.IntegerField()),
                ('stock_vac_covid', models.IntegerField()),
                ('stock_vac_gripe', models.IntegerField()),
            ],
        ),
    ]
