# Generated by Django 3.0.5 on 2022-05-27 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20220526_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacunatorio',
            name='vacunatorio_unidad',
        ),
    ]
