# Generated by Django 3.0.5 on 2022-06-09 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_vacunatorio_vacunatorio_unidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logeado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuarioLogeado', models.IntegerField(max_length=8)),
            ],
        ),
    ]
