# Generated by Django 3.0.5 on 2022-06-09 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_logeado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logeado',
            name='usuarioLogeado',
            field=models.IntegerField(),
        ),
    ]
