# Generated by Django 3.0.5 on 2022-06-09 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20220608_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='logeado',
            name='numId',
            field=models.IntegerField(default=int),
            preserve_default=False,
        ),
    ]
