# Generated by Django 3.0.5 on 2022-06-09 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_logeado_numid'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudTurnoFA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.IntegerField()),
                ('numId', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
