# Generated by Django 3.0.5 on 2022-06-09 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20220609_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='vac_Covid_turno2',
            field=models.DateTimeField(null=True),
        ),
    ]
