# Generated by Django 3.0.5 on 2022-06-09 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20220609_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='vac_Amarilla_turno',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='vac_Covid_turno1',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='vac_Gripe_turno',
            field=models.DateTimeField(null=True),
        ),
    ]
