# Generated by Django 3.0.5 on 2022-06-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20220609_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='paciente_apellido',
            field=models.CharField(max_length=200),
        ),
    ]
