# Generated by Django 3.0.5 on 2022-06-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20220609_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='paciente_apellido',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='paciente_nombre',
            field=models.CharField(max_length=20),
        ),
    ]
