# Generated by Django 3.0.5 on 2022-06-18 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20220617_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='administrador_codigo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='contraseña',
            field=models.CharField(max_length=200),
        ),
    ]
