# Generated by Django 3.0.5 on 2022-06-20 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_turnofaprobados'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TurnoFAprobados',
            new_name='TurnoFAAprobados',
        ),
    ]
