# Generated by Django 3.0.5 on 2022-06-20 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_auto_20220620_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudturnofa',
            name='edad',
            field=models.IntegerField(default=int),
            preserve_default=False,
        ),
    ]
