# Generated by Django 4.1.dev20220516154624 on 2022-06-21 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_solicitudturnofa_edad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_dni', models.CharField(max_length=200)),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=20)),
            ],
        ),
    ]
