# Generated by Django 4.1.dev20220516154624 on 2022-07-04 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_dni'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente_ST',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pacienteST_dni', models.CharField(max_length=200)),
                ('pacienteST_nombre', models.CharField(max_length=200)),
                ('pacienteST_apellido', models.CharField(max_length=20)),
                ('pacienteST_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
