# Generated by Django 4.1.dev20220516154624 on 2022-07-04 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_paciente_st'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente_st',
            name='vac_Amarilla_aplicada',
            field=models.SmallIntegerField(choices=[(1, 'Si'), (2, 'No')], default=2),
        ),
        migrations.AddField(
            model_name='paciente_st',
            name='vac_Amarilla_asistencia',
            field=models.SmallIntegerField(choices=[(1, 'Si'), (2, 'No')], default=2),
        ),
        migrations.AddField(
            model_name='paciente_st',
            name='vac_Amarilla_turno',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='paciente_st',
            name='vac_Covid1_aplicada',
            field=models.SmallIntegerField(choices=[(1, 'Si'), (2, 'No')], default=2),
        ),
        migrations.AddField(
            model_name='paciente_st',
            name='vac_Covid1era_asistencia',
            field=models.SmallIntegerField(choices=[(1, 'Si'), (2, 'No')], default=2),
        ),
        migrations.AddField(
            model_name='paciente_st',
            name='vac_Covid2_aplicada',
            field=models.SmallIntegerField(choices=[(1, 'Si'), (2, 'No')], default=2),
        ),
        migrations.AddField(
            model_name='paciente_st',
            name='vac_Covid2da_asistencia',
            field=models.SmallIntegerField(choices=[(1, 'Si'), (2, 'No')], default=2),
        ),
        migrations.AddField(
            model_name='paciente_st',
            name='vac_Covid_turno1',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='paciente_st',
            name='vac_Covid_turno2',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='paciente_st',
            name='vac_Gripe_aplicada',
            field=models.SmallIntegerField(choices=[(1, 'Si'), (2, 'No')], default=2),
        ),
        migrations.AddField(
            model_name='paciente_st',
            name='vac_Gripe_turno',
            field=models.DateTimeField(null=True),
        ),
    ]
